//! Golden parity tests against the legacy Python implementation.
//!
//! Goldens are generated by `python tests/golden/generate_legacy_goldens.py`
//! at the repository root and stored under tests/golden/legacy/.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use tree_plus_core::{extract_components, from_seeds, TreePlusConfig};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root")
}

/// Extensions and file names covered by the version-1 scope.
fn in_v1_scope(path: &str) -> bool {
    let name = path.rsplit('/').next().unwrap_or(path);
    let lower = name.to_lowercase();
    if name == "Makefile" || name == "Justfile" || name.starts_with(".env") {
        return true;
    }
    if name.ends_with("Cargo.toml") || name.ends_with("pyproject.toml") {
        return true;
    }
    const V1_EXTS: &[&str] = &[
        ".py",
        ".pyi",
        ".rs",
        ".go",
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".c",
        ".h",
        ".cc",
        ".cpp",
        ".cu",
        ".cuh",
        ".hpp",
        ".md",
        ".markdown",
        ".mdx",
        ".mdc",
        ".json",
        ".jsonl",
        ".yml",
        ".yaml",
        ".csv",
        ".txt",
        ".db",
        ".sqlite",
    ];
    V1_EXTS.iter().any(|e| lower.ends_with(e))
}

/// Intentional differences from the legacy output, documented in
/// docs/rust-port-differences.md. The expectations are adjusted precisely so
/// any other drift still fails.
fn apply_intentional_differences(rel: &str, expected: Vec<String>) -> Vec<String> {
    match rel {
        // The TensorFlow flag special case was deliberately dropped; the
        // remaining C components must still match exactly.
        "tests/more_languages/group6/tensorflow_flags.h" => expected
            .into_iter()
            .filter(|c| {
                !(c.starts_with("Flag('")
                    || c.starts_with("TF_DECLARE_FLAG('")
                    || c.starts_with("TF_PY_DECLARE_FLAG('"))
            })
            .collect(),
        // The legacy regex mistook a string literal containing the word
        // "function" for a function definition; tree-sitter does not.
        "tests/more_languages/group1/test.ts" => expected
            .into_iter()
            .filter(|c| c != "  return(\"Standalone function with parameters\")")
            .collect(),
        _ => expected,
    }
}

fn parse_golden(path: &Path) -> (String, Vec<String>) {
    let raw = std::fs::read_to_string(path).expect("read golden");
    let value: serde_json::Value = serde_json::from_str(&raw).expect("parse golden json");
    let rel = value["path"].as_str().expect("path").to_string();
    let components = value["components"]
        .as_array()
        .expect("components")
        .iter()
        .map(|v| v.as_str().expect("component str").to_string())
        .collect();
    (rel, components)
}

#[test]
fn components_match_legacy_goldens() {
    let root = repo_root();
    let goldens_dir = root.join("tests/golden/legacy/components");
    let mut failures: BTreeMap<String, (Vec<String>, Vec<String>)> = BTreeMap::new();
    let mut checked = 0;
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&goldens_dir)
        .expect("goldens generated? run python tests/golden/generate_legacy_goldens.py")
        .flatten()
        .map(|e| e.path())
        .collect();
    entries.sort();
    for golden_path in entries {
        let (rel, expected) = parse_golden(&golden_path);
        if !in_v1_scope(&rel) {
            continue;
        }
        let expected = apply_intentional_differences(&rel, expected);
        let actual = extract_components(&root.join(&rel), false);
        checked += 1;
        if actual != expected {
            failures.insert(rel, (expected, actual));
        }
    }
    assert!(
        checked > 50,
        "expected to check many fixtures, got {checked}"
    );
    if !failures.is_empty() {
        let mut report = format!(
            "{} of {} v1-scope fixtures differ from legacy goldens:\n",
            failures.len(),
            checked
        );
        for (rel, (expected, actual)) in &failures {
            report.push_str(&format!(
                "--- {rel}\n  expected ({}): {:?}\n  actual   ({}): {:?}\n",
                expected.len(),
                expected,
                actual.len(),
                actual
            ));
        }
        panic!("{report}");
    }
}

/// chdir is process-global; serialize the tree tests.
static CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

fn tree_parity(name: &str, seeds: &[&str]) {
    let root = repo_root();
    // trees_v1: legacy renders with non-v1 extractors stubbed (deferred
    // languages keep their counts and markers but lose components)
    let golden =
        std::fs::read_to_string(root.join(format!("tests/golden/legacy/trees_v1/{name}.txt")))
            .expect("tree golden");
    // legacy goldens were produced with cwd at the repo root
    let _guard = CWD_LOCK
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let original = std::env::current_dir().expect("cwd");
    std::env::set_current_dir(&root).expect("chdir to repo root");
    let seeds: Vec<String> = seeds.iter().map(|s| s.to_string()).collect();
    let config = TreePlusConfig::default();
    let tree = from_seeds(&seeds, &config);
    let rendered = tree.into_str();
    std::env::set_current_dir(original).expect("chdir back");
    assert_eq!(
        rendered, golden,
        "tree render for {name} differs from legacy golden"
    );
}

#[test]
fn tree_path_to_test_matches() {
    tree_parity("path_to_test", &["tests/path_to_test"]);
}

#[test]
fn tree_dot_dot_matches() {
    tree_parity("dot_dot", &["tests/dot_dot"]);
}

#[test]
fn tree_multi_seed_matches() {
    tree_parity(
        "multi_seed",
        &["tests/path_to_test", "tests/more_languages/group1"],
    );
}

#[test]
fn tree_group4_matches() {
    tree_parity("more_languages_group4", &["tests/more_languages/group4"]);
}

#[test]
fn tree_group6_matches() {
    tree_parity("more_languages_group6", &["tests/more_languages/group6"]);
}

#[test]
fn tree_more_languages_matches() {
    tree_parity("more_languages", &["tests/more_languages"]);
}

#[test]
fn tree_group1_matches() {
    tree_parity("more_languages_group1", &["tests/more_languages/group1"]);
}

#[test]
fn tree_group2_matches() {
    tree_parity("more_languages_group2", &["tests/more_languages/group2"]);
}

#[test]
fn tree_group3_matches() {
    tree_parity("more_languages_group3", &["tests/more_languages/group3"]);
}

#[test]
fn tree_group5_matches() {
    tree_parity("more_languages_group5", &["tests/more_languages/group5"]);
}

#[test]
fn tree_group7_matches() {
    tree_parity("more_languages_group7", &["tests/more_languages/group7"]);
}

#[test]
fn tree_group_todo_matches() {
    tree_parity(
        "more_languages_group_todo",
        &["tests/more_languages/group_todo"],
    );
}

#[test]
fn tree_group_lisp_matches() {
    tree_parity(
        "more_languages_group_lisp",
        &["tests/more_languages/group_lisp"],
    );
}
